// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.178.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Cron.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;

    using global::Naos.Cron;

    using global::OBeautifulCode.AutoFakeItEasy;
    using global::OBeautifulCode.Math.Recipes;

    /// <summary>
    /// The default (code generated) Dummy Factory.
    /// Derive from this class to add any overriding or custom registrations.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.178.0")]
#if !NaosCronSolution
    internal
#else
    public
#endif
    abstract class DefaultCronDummyFactory : IDummyFactory
    {
        public DefaultCronDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new DailyScheduleInUtc
                             {
                                 Hour   = A.Dummy<int>(),
                                 Minute = A.Dummy<int>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ExpressionSchedule
                             {
                                 CronExpression = A.Dummy<string>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new HourlySchedule
                             {
                                 Minute = A.Dummy<int>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new IntervalSchedule
                             {
                                 Interval = A.Dummy<TimeSpan>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new MonthlyScheduleInUtc
                             {
                                 DaysOfMonth = A.Dummy<int[]>(),
                                 Hour        = A.Dummy<int>(),
                                 Minute      = A.Dummy<int>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullSchedule());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(DailyScheduleInUtc),
                        typeof(ExpressionSchedule),
                        typeof(HourlySchedule),
                        typeof(IntervalSchedule),
                        typeof(MonthlyScheduleInUtc),
                        typeof(NullSchedule),
                        typeof(WeeklyScheduleInUtc),
                        typeof(YearlyScheduleInUtc)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (ScheduleBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new WeeklyScheduleInUtc
                             {
                                 DaysOfWeek = A.Dummy<DayOfWeek[]>(),
                                 Hour       = A.Dummy<int>(),
                                 Minute     = A.Dummy<int>(),
                             });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new YearlyScheduleInUtc
                             {
                                 MonthsOfYear = A.Dummy<MonthOfYear[]>(),
                                 DaysOfMonth  = A.Dummy<int[]>(),
                                 Hour         = A.Dummy<int>(),
                                 Minute       = A.Dummy<int>(),
                             });
        }

        /// <inheritdoc />
        public Priority Priority => new FakeItEasy.Priority(1);

        /// <inheritdoc />
        public bool CanCreate(Type type)
        {
            return false;
        }

        /// <inheritdoc />
        public object Create(Type type)
        {
            return null;
        }
    }
}